### ISSUE TITLE
[Non-Bug] Example/test code?

### ISSUE THREAD

**Issue by SuperFromND** [bluenviron/mediacommon#165]
Hello! Sorry in advance if this question is maybe mis-informed/the wrong place to ask.

I'm a hobby developer for the [Ikemen GO](https://ikemen-engine.github.io/) fighting game engine, and a semi-commonly requested feature for us is video playback support, for in-game cutscenes and the like. There's not really a good solution for playing back video files in Go directly (all the examples I can find) use FFmpeg, which is a pain to work with in Go especially on Windows, not to mention gigantic in file size unless you self-compile), which lead me to this repository.

From what I can tell this repo is part of some larger projects, all of which *seem* to be capable of playing back video files... for _servers_, as opposed to what I'm looking for. What I want to do is take an input video file (preferrably an MP4 with H.264 encoding, but AV1 is also in the cards since its more open) and then have it spit out RGBA frames in a similar manner to [this ffmpeg-based Reisen library](https://github.com/zergon321/reisen). (See [this unfinished proof-of-concept](https://github.com/ikemen-engine/Ikemen-GO/compare/develop...samhocevar-forks:ikemen-go:video-playback) and [this GitHub Discussion](https://github.com/ikemen-engine/Ikemen-GO/discussions/849) if you need further context.)

Is there any good "minimum test case" samples/projects that use these libraries? And if not, would it be possible for such a sample case to be created?

**Comment by aler9** [comment]
Hello @SuperFromND, in order to write a video player with Go or any other language you need two building blocks: a container parser, which is able to extract H264 access units (or any other kind of data) from MP4s, and a video decoder, which converts H264 access units into YUV frames (and also a YUV->RGBA converter if you want RGBA).

The container part is computationally-inexpensive and can be written in pure Go - my advice is to use the [go-mp4](https://github.com/abema/go-mp4) library that we're also using here, although we're using it to parse fragmented-MP4s only, which are unfit for playback. It requires some knowledge on how MP4s are structured, but other than that, it's quite easy to use.

The problem here is the decoding part, which we do not do here (it's Chrome or VLC or FFmpeg that actually decodes the video on the client side) and has two main issues:

* it's complex and computationally expensive
* it's covered by patents

Decoders are split into two categories: hardware and software. Software decoders are quite intricate (basically they are impossible to rewrite in another language from scratch, or at cost of a huge performance loss), they are codec-dependent and they partially solve the patent issue (openh264 provides free usage for open source projects - regarding other ones, you are in a grey area).

Hardware encoders use ready-to-use calls from the GPU and moves the patent burden on the hardware (basically, cost is included in hardware price). Hardware encoders can of course be enabled on some hardware only, therefore, the decoder should be switchable at will.

Therefore: regarding the decoding part, you need a software which is able to switch transparently from an underlying library to another one and that is able to handle all the complexity of the video decoding world. Because you do not want to mess with that unless it's the core feature of your project.

This is the reason why FFmpeg or GStreamer are used as backbone of most video players. You can go a step forward and use directly a H264 decoder (like openh264) but in this way you are also in charge of handling all possible codecs and all possible hardware.

All i can provide is a lightweight wrapper around libav that is able to decode H264 frames - the advantage is that it does not have any dependency, so you do not have to depend on Reisen or go-ffmpeg or any other wrapper (and size will be slightly smaller):

https://github.com/bluenviron/gortsplib/blob/main/examples/client-play-format-h264/h264_decoder.go

Regarding Windows builds, if you want to get away from FFmpeg / libav, you can use build flags to enable a Windows-only solution based on Microsoft Media Foundation, that is shipped with the operative system and it does not require dependencies.

**Comment by SuperFromND** [comment]
Thank you for the really detailed response! I'll close this for now. :>
