### ISSUE TITLE
Picking a new MaxNALUSize

### ISSUE THREAD

**Issue by database64128** [bluenviron/mediacommon#35]
After more usage, it turns out that the newly raised (#30) MaxNALUSize is still not enough for 2160p60 streaming:

```
unable to decode AVCC: NALU size (4298040) is too big, maximum is 4194304
```

Before opening another pull request to raise the limit again, I would like to understand more about the effects of this value on memory usage. Would it be ok to just double it?

**Comment by aler9** [comment]
Hello, that variable doesn't influence memory usage, it's a limit on the maximum available memory in order to prevent people from creating specially-crafted packets that can crash software that depends on this library.

In case of RTSP / WebRTC / SRT / UDP, only one NALU at a time is routed from publisher to readers, therefore the maximum RAM occupied by a stream is MaxNALUSize * (maximum write queue size).

 In case of HLS, a sequence of NALUs is kept into memory because HLS works by serving segments of NALUs, therefore the maximum RAM occupied by a stream is MaxNALUSize * segment duration * number of segments.

**Comment by aler9** [comment]
BTW i've renamed the variable into MaxAccessUnitSize in order to apply it to the entire access unit. An access unit is a sequence of NALUs referred to the same time instant.

**Comment by database64128** [comment]
Thanks for the detailed explanation. Do you plan to update the limit yourself? I'd be happy to test it afterwards.
